server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dcbapp
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

welcome:
  message: Welcome to Daily Code Buffer!!

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Daily Code Buffer!!

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Daily Code Buffer!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Daily Code Buffer!!
